#!/usr/bin/env bash
# Boot a Surfpool localnet validator with all five AR.IO programs preloaded.
#
# What this does:
#   1. (Re-)build BPF artifacts via `build-sbf.sh --sync` so declare_id!() and
#      target/deploy/<crate>-keypair.json agree (canonical localnet flow).
#   2. Stage Metaplex Core's mpl_core.so into target/deploy/ — ario-arns and
#      ario-ant CPI into it; without this preload the localnet rejects those
#      paths with AccountNotExecutable.
#   3. Launch Surfpool with each program loaded via `--bpf-program <id> <so>`,
#      mainnet-style SVM feature gates (see localnet/surfpool-svm-features.sh),
#      and JSON-RPC on the default port (8899).
#   4. Write program IDs + the RPC URL to localnet/out/localnet.env so
#      downstream tooling (SDK tests, migration import, indexer tests) can
#      `source` it.
#
# Env toggles:
#   SKIP_BUILD=1                                     # use existing target/deploy/*.so
#   SURFPOOL_PORT=8899                               # rpc port (default 8899)
#   SURFPOOL_SKIP_MAINNET_INACTIVE_DISABLES=1        # see localnet/surfpool-svm-features.sh
#   SURFPOOL_ENABLE_ALL_SVM_FEATURES=1
#
# Surfpool (https://github.com/solana-foundation/surfpool) must be on PATH.
# Install: `cargo install surfpool` or download a release binary.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export PATH="${HOME}/.local/share/solana/install/active_release/bin:${PATH}"

SURFPOOL_PORT="${SURFPOOL_PORT:-8899}"
OUT_DIR="$REPO_ROOT/localnet/out"
mkdir -p "$OUT_DIR"

# 1. Build (or reuse) BPF artifacts.
if [[ "${SKIP_BUILD:-0}" != "1" ]]; then
  echo "[start-localnet] Building BPF programs (build-sbf.sh --sync)..."
  bash "$REPO_ROOT/build-sbf.sh" --sync
else
  echo "[start-localnet] SKIP_BUILD=1; reusing target/deploy/*.so"
fi

# 2. Stage mpl_core.so for ario-arns / ario-ant CPI.
MPL_FIXTURE="$REPO_ROOT/programs/ario-arns/tests/fixtures/mpl_core.so"
if [[ -f "$MPL_FIXTURE" ]]; then
  cp "$MPL_FIXTURE" "$REPO_ROOT/target/deploy/mpl_core.so"
else
  echo "[start-localnet] WARN: mpl_core.so fixture missing at $MPL_FIXTURE" >&2
fi

# Metaplex Core's canonical mainnet program ID — Surfpool needs it explicitly
# so client-side hard-coded references (`mpl-core` SDK, ario-arns CPI target)
# resolve.
MPL_CORE_ID="CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"

# 3. Resolve our five program IDs from the deploy keypairs (build-sbf.sh
#    --sync just rewrote the source declare_id!() to match).
declare -A PROGRAMS=(
  [ario_core]="$REPO_ROOT/target/deploy/ario_core-keypair.json"
  [ario_gar]="$REPO_ROOT/target/deploy/ario_gar-keypair.json"
  [ario_arns]="$REPO_ROOT/target/deploy/ario_arns-keypair.json"
  [ario_ant]="$REPO_ROOT/target/deploy/ario_ant-keypair.json"
  [ario_ant_escrow]="$REPO_ROOT/target/deploy/ario_ant_escrow-keypair.json"
)

# 4. Surfpool flags assembled per https://github.com/solana-foundation/surfpool.
#    `surfpool start` defaults to mainnet-fork — we want a clean local cluster.
ARGS=(start --no-tui --rpc-port "$SURFPOOL_PORT")

for prog in ario_core ario_gar ario_arns ario_ant ario_ant_escrow; do
  kp="${PROGRAMS[$prog]}"
  so="$REPO_ROOT/target/deploy/${prog}.so"
  if [[ ! -f "$kp" || ! -f "$so" ]]; then
    echo "[start-localnet] missing artifact for $prog: kp=$kp so=$so" >&2
    exit 1
  fi
  pid="$(solana-keygen pubkey "$kp")"
  ARGS+=(--bpf-program "$pid" "$so")
  declare "${prog^^}_ID=$pid"
done

if [[ -f "$REPO_ROOT/target/deploy/mpl_core.so" ]]; then
  ARGS+=(--bpf-program "$MPL_CORE_ID" "$REPO_ROOT/target/deploy/mpl_core.so")
fi

# 5. Layer on the canonical SVM feature flags (mainnet-style by default).
if [[ -f "$REPO_ROOT/localnet/surfpool-svm-features.sh" ]]; then
  # shellcheck source=../localnet/surfpool-svm-features.sh
  source "$REPO_ROOT/localnet/surfpool-svm-features.sh"
  ario_surfpool_svm_extra_start_args
  if [[ "${#SURFPOOL_EXTRA_START_ARGS[@]:-0}" -gt 0 ]]; then
    ARGS+=("${SURFPOOL_EXTRA_START_ARGS[@]}")
  fi
fi

# 6. Persist localnet.env so downstream tooling can source it.
cat > "$OUT_DIR/localnet.env" <<EOF
# Generated by scripts/start-localnet.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
ARIO_RPC_URL="http://127.0.0.1:${SURFPOOL_PORT}"
ARIO_WS_URL="ws://127.0.0.1:${SURFPOOL_PORT}"
ARIO_CORE_PROGRAM_ID="${ARIO_CORE_ID}"
ARIO_GAR_PROGRAM_ID="${ARIO_GAR_ID}"
ARIO_ARNS_PROGRAM_ID="${ARIO_ARNS_ID}"
ARIO_ANT_PROGRAM_ID="${ARIO_ANT_ID}"
ARIO_ANT_ESCROW_PROGRAM_ID="${ARIO_ANT_ESCROW_ID}"
MPL_CORE_PROGRAM_ID="${MPL_CORE_ID}"
EOF

echo "[start-localnet] Program IDs:"
echo "  ario-core:        ${ARIO_CORE_ID}"
echo "  ario-gar:         ${ARIO_GAR_ID}"
echo "  ario-arns:        ${ARIO_ARNS_ID}"
echo "  ario-ant:         ${ARIO_ANT_ID}"
echo "  ario-ant-escrow:  ${ARIO_ANT_ESCROW_ID}"
echo "  mpl-core:         ${MPL_CORE_ID}"
echo "[start-localnet] env written to $OUT_DIR/localnet.env"
echo "[start-localnet] launching: surfpool ${ARGS[*]}"
echo

exec surfpool "${ARGS[@]}"
